import { DemoUser, FleetUnit, PartRecord, RepairRecord, ServiceRecord, WorksheetEntry } from "@/lib/types";

export const demoUsers: DemoUser[] = [
  { email: "admin@turbo.local", password: "admin123", role: "admin", name: "Admin User" },
  { email: "manager@turbo.local", password: "manager123", role: "manager", name: "Workshop Manager" },
  { email: "stores@turbo.local", password: "stores123", role: "stores", name: "Stores User" },
];

export const fleetUnits: FleetUnit[] = [
  ...Array.from({ length: 13 }, (_, i) => ({
    id: `fel-${i + 1}`,
    fleetNumber: `FEL ${i + 1}`,
    type: "Front End Loader",
    category: "Yellow Machine",
    status: i < 2 ? "In Workshop" : "Running",
    location: i < 2 ? "Main Workshop" : "Pit A",
    km: 0,
    hours: 4500 + (i * 220),
    nextServiceHours: 5000 + (i * 220),
  })),
  { id: "tlb-01", fleetNumber: "TLB 01", type: "Backhoe Loader", category: "Yellow Machine", status: "Running", location: "Plant Yard", km: 12240, hours: 3180, nextServiceKm: 15000, nextServiceHours: 3500 },
  { id: "tlb-02", fleetNumber: "TLB 02", type: "Backhoe Loader", category: "Yellow Machine", status: "Under Service", location: "Workshop Bay 2", km: 14210, hours: 4010, nextServiceKm: 15000, nextServiceHours: 4500 },
  { id: "tlb-03", fleetNumber: "TLB 03", type: "Backhoe Loader", category: "Yellow Machine", status: "Running", location: "Stockpile", km: 9030, hours: 2760, nextServiceKm: 10000, nextServiceHours: 3000 },
  { id: "todano", fleetNumber: "Todano", type: "Crane", category: "Lifting", status: "Running", location: "Main Yard", km: 88215, hours: 0 },
  { id: "hc-01", fleetNumber: "HC 01", type: "Support Unit", category: "Support", status: "Parked", location: "Overflow Yard", km: 0, hours: 1210 },
  { id: "tmt-01", fleetNumber: "TMT 01", type: "Plant Unit", category: "Plant", status: "Running", location: "Quarry", km: 0, hours: 5321 },
  { id: "tmt-02", fleetNumber: "TMT 02", type: "Plant Unit", category: "Plant", status: "Running", location: "Quarry", km: 0, hours: 4888 },
  { id: "tt01", fleetNumber: "TT01", type: "Support Unit", category: "Support", status: "Running", location: "Dam Site", km: 0, hours: 2140 },
  { id: "tmd-01", fleetNumber: "TMD 01", type: "Dozer", category: "Yellow Machine", status: "Running", location: "Cut 1", km: 0, hours: 6120 },
  { id: "tmd-02", fleetNumber: "TMD 02", type: "Dozer", category: "Yellow Machine", status: "Breakdown", location: "Workshop Bay 3", km: 0, hours: 5840 },
  { id: "tmd-03", fleetNumber: "TMD 03", type: "Dozer", category: "Yellow Machine", status: "Running", location: "Cut 2", km: 0, hours: 5580 },
  { id: "tmd-05", fleetNumber: "TMD 05", type: "Dozer", category: "Yellow Machine", status: "Waiting Parts", location: "Workshop Bay 4", km: 0, hours: 6900 },
  { id: "tmd-06", fleetNumber: "TMD 06", type: "Dozer", category: "Yellow Machine", status: "Running", location: "Dam Wall", km: 0, hours: 5021 },
  { id: "tmd-07", fleetNumber: "TMD07", type: "Dozer", category: "Yellow Machine", status: "Running", location: "Bot Plant", km: 0, hours: 4780 },
  { id: "tmd-08", fleetNumber: "TMD 08", type: "Dozer", category: "Yellow Machine", status: "Under Service", location: "Main Workshop", km: 0, hours: 7332 },
  { id: "d07", fleetNumber: "D07", type: "Dozer", category: "Yellow Machine", status: "Running", location: "Dam Site", km: 0, hours: 3550 },
  ...Array.from({ length: 7 }, (_, i) => ({
    id: `tex-${i + 1}`,
    fleetNumber: `TEX 0${i + 1}`,
    type: "Excavator",
    category: "Yellow Machine",
    status: i === 4 ? "Breakdown" : "Running",
    location: i === 4 ? "Workshop Bay 1" : `Pit ${String.fromCharCode(65 + (i % 3))}`,
    km: 0,
    hours: 4200 + (i * 315),
    nextServiceHours: 4500 + (i * 315),
  })),
  { id: "tmg-01", fleetNumber: "TMG 01", type: "Motor Grader", category: "Yellow Machine", status: "Running", location: "Roads", km: 0, hours: 4175 },
  { id: "tlg-01", fleetNumber: "TLG 01", type: "Loader", category: "Yellow Machine", status: "Running", location: "Stockpile", km: 0, hours: 2455 },
  { id: "tlg-02", fleetNumber: "TLG 02", type: "Loader", category: "Yellow Machine", status: "Running", location: "Stockpile", km: 0, hours: 2690 },
  { id: "tmr-01", fleetNumber: "TMR 01", type: "Roller", category: "Yellow Machine", status: "Parked", location: "Yard", km: 0, hours: 1801 },
  { id: "leega-dam", fleetNumber: "LEEGA 20KVA (DAM)", type: "Generator", category: "Power", status: "Running", location: "Dam Camp", km: 0, hours: 962 },
  { id: "leega-bot", fleetNumber: "LEEGA 20KVA (BOT)", type: "Generator", category: "Power", status: "Running", location: "Botswana Camp", km: 0, hours: 888 },
  { id: "nexus-gen", fleetNumber: "NEXUS GEN", type: "Generator", category: "Power", status: "Running", location: "Stores", km: 0, hours: 1130 },
  { id: "volvo-out", fleetNumber: "Volvo Gen (outside)", type: "Generator", category: "Power", status: "Running", location: "Outside Plant", km: 0, hours: 1630 },
  { id: "volvo-in", fleetNumber: "Volvo Gen (incont)", type: "Generator", category: "Power", status: "Running", location: "Container Plant", km: 0, hours: 1452 },
  { id: "launtop-2", fleetNumber: "LAUNTOP GEN 2", type: "Generator", category: "Power", status: "Parked", location: "Stores", km: 0, hours: 620 },
  { id: "green-gen", fleetNumber: "GREEN GEN", type: "Generator", category: "Power", status: "Running", location: "Admin", km: 0, hours: 784 },
  { id: "bundu", fleetNumber: "Bundu Genset", type: "Generator", category: "Power", status: "Running", location: "Workshop", km: 0, hours: 430 },
  { id: "tg-08", fleetNumber: "TG 08 Perkins Admin", type: "Generator", category: "Power", status: "Running", location: "Admin", km: 0, hours: 2050 },
  { id: "tg-10", fleetNumber: "TG 10 Nexus Botswana", type: "Generator", category: "Power", status: "Running", location: "Botswana", km: 0, hours: 1984 },
  { id: "tw-01", fleetNumber: "TW 01", type: "Water Bowser", category: "Support", status: "Running", location: "Haul Road", km: 15880, hours: 0, nextServiceKm: 20000 },
  { id: "tw-02", fleetNumber: "TW 02", type: "Water Bowser", category: "Support", status: "Running", location: "Haul Road", km: 12100, hours: 0, nextServiceKm: 15000 },
  { id: "tw-03", fleetNumber: "TW 03", type: "Water Bowser", category: "Support", status: "Under Service", location: "Workshop Bay 5", km: 18620, hours: 0, nextServiceKm: 20000 },
  { id: "tw-07", fleetNumber: "TW 07", type: "Water Bowser", category: "Support", status: "Running", location: "Dam Wall", km: 14650, hours: 0, nextServiceKm: 18000 },
  { id: "tw-08", fleetNumber: "TW 08", type: "Water Bowser", category: "Support", status: "Running", location: "Dam Wall", km: 9910, hours: 0, nextServiceKm: 12000 },
  { id: "tw-09", fleetNumber: "TW 09", type: "Water Bowser", category: "Support", status: "Waiting Parts", location: "Workshop Bay 6", km: 22100, hours: 0, nextServiceKm: 24000 },
  { id: "tdr-01", fleetNumber: "TDR 01 (drill rig)", type: "Drill Rig", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 2890 },
  { id: "tdc-01", fleetNumber: "TDC 01", type: "Compressor", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 2200 },
  { id: "tdr-02", fleetNumber: "TDR 02 (drill rig)", type: "Drill Rig", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 3012 },
  { id: "tdc-02", fleetNumber: "TDC 02", type: "Compressor", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 2320 },
  { id: "tdr-03", fleetNumber: "TDR 03", type: "Drill Rig", category: "Plant", status: "Under Service", location: "Workshop", km: 0, hours: 2540 },
  { id: "tdc-03", fleetNumber: "TDC 03", type: "Compressor", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 2410 },
  { id: "tdc-04", fleetNumber: "TDC 04", type: "Compressor", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 1980 },
  { id: "tcd-01", fleetNumber: "TCD 01", type: "Drill Support", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 1750 },
  { id: "tcd-rig-01", fleetNumber: "TCD RIG 01", type: "Rig Support", category: "Plant", status: "Running", location: "Blast Area", km: 0, hours: 1890 },
  ...Array.from({ length: 7 }, (_, i) => ({
    id: `tlt-${i + 1}`,
    fleetNumber: `TLT 0${i + 1}`,
    type: "Telehandler",
    category: "Lifting",
    status: i === 5 ? "Breakdown" : "Running",
    location: i === 5 ? "Workshop" : "Civil Works",
    km: 4600 + (i * 550),
    hours: 1750 + (i * 140),
    nextServiceKm: 5000 + (i * 550),
    nextServiceHours: 2000 + (i * 140),
  })),
  { id: "tfl-01", fleetNumber: "TFL 01", type: "Forklift", category: "Lifting", status: "Running", location: "Stores", km: 0, hours: 2180 },
  { id: "tfl-02", fleetNumber: "TFL 02", type: "Forklift", category: "Lifting", status: "Running", location: "Stores", km: 0, hours: 1960 },
  { id: "agj-9529", fleetNumber: "AGJ 9529 (TMA 01)", type: "Service Vehicle", category: "Support", status: "Running", location: "Admin", km: 138220, hours: 0, nextServiceKm: 145000 },
  { id: "tct-01", fleetNumber: "TCT 01", type: "Compactor", category: "Plant", status: "Running", location: "Dam Wall", km: 0, hours: 2250 },
  { id: "tcm-01", fleetNumber: "TCM 01", type: "Compactor", category: "Plant", status: "Running", location: "Dam Wall", km: 0, hours: 2440 },
  { id: "tfb-01", fleetNumber: "TFB 01", type: "Fuel Bowser", category: "Support", status: "Running", location: "Fuel Bay", km: 17580, hours: 0, nextServiceKm: 20000 },
  { id: "mwb-01", fleetNumber: "MWB 01", type: "Water Bowser", category: "Support", status: "Running", location: "Processing Plant", km: 18320, hours: 0, nextServiceKm: 20000 },
];

export const repairs: RepairRecord[] = [
  {
    id: "rep-001",
    unitId: "tmd-02",
    fault: "Left final drive oil leak and reduced travel power.",
    workDone: "Machine washed, leak traced, final drive drained and inspected.",
    workToBeDone: "Replace duo cone seal and inspect bearings.",
    assignedTo: "Chargehand Moyo",
    openedAt: "2026-04-10",
    status: "Open",
  },
  {
    id: "rep-002",
    unitId: "tex-05",
    fault: "Boom cylinder bypassing under load.",
    workDone: "Pressure tested cylinder and removed for strip inspection.",
    workToBeDone: "Awaiting seal kit approval.",
    assignedTo: "Foreman Ncube",
    openedAt: "2026-04-12",
    status: "Waiting Parts",
  },
  {
    id: "rep-003",
    unitId: "tlt-06",
    fault: "Starter not cranking consistently.",
    workDone: "Battery and earth circuit tested.",
    workToBeDone: "Fit new starter and retest charging system.",
    assignedTo: "Chargehand Dube",
    openedAt: "2026-04-13",
    status: "Open",
  },
];

export const services: ServiceRecord[] = [
  {
    id: "srv-001",
    unitId: "fel-01",
    serviceType: "500h Service",
    workDone: "Engine oil and filters changed, greasing completed, articulation pins checked.",
    serviceDate: "2026-04-08",
    km: 0,
    hours: 4950,
    technician: "Team A",
  },
  {
    id: "srv-002",
    unitId: "tw-03",
    serviceType: "20 000km Service",
    workDone: "Engine service, brake inspection, wheel nut torque check.",
    serviceDate: "2026-04-11",
    km: 18620,
    hours: 0,
    technician: "Team B",
  },
];

export const parts: PartRecord[] = [
  { id: "part-001", partName: "Hydraulic Hose 1in", partNumber: "HH-100", quantity: 6, reorderLevel: 4, status: "In Stock", unitPrice: 95 },
  { id: "part-002", partName: "Dozer Track Seal Kit", partNumber: "DSK-450", quantity: 0, reorderLevel: 2, status: "To Order", unitPrice: 430 },
  { id: "part-003", partName: "Excavator Boom Seal Kit", partNumber: "BSK-320", quantity: 0, reorderLevel: 1, status: "On Funding", unitPrice: 290 },
  { id: "part-004", partName: "15W40 Engine Oil 20L", partNumber: "OIL-1540", quantity: 18, reorderLevel: 10, status: "In Stock", unitPrice: 72 },
  { id: "part-005", partName: "Fuel Filter", partNumber: "FF-210", quantity: 3, reorderLevel: 8, status: "To Order", unitPrice: 18 },
];

export const worksheets: WorksheetEntry[] = [
  {
    id: "ws-001",
    unitId: "tmd-02",
    user: "B. Sibanda",
    workType: "Repair",
    description: "Removed belly plates and cleaned final drive area for strip.",
    workDate: "2026-04-11",
    hoursSpent: 3.5,
  },
  {
    id: "ws-002",
    unitId: "tw-03",
    user: "L. Moyo",
    workType: "Service",
    description: "Completed full truck service and brake adjustment.",
    workDate: "2026-04-11",
    hoursSpent: 4,
  },
  {
    id: "ws-003",
    unitId: "fel-01",
    user: "T. Dube",
    workType: "Inspection",
    description: "Checked articulation play and steering hoses.",
    workDate: "2026-04-12",
    hoursSpent: 1.5,
  },
];
